In [1]:
import torch

In [6]:
tmp = torch.arange(10)
print(tmp)
half1 = tmp[:5]
half2 = tmp[5:]
torch.cat((-half2, half1), dim=-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([-5, -6, -7, -8, -9,  0,  1,  2,  3,  4])

In [9]:
one, two = tmp.reshape(-1, 2).split(1, dim=-1)
tmp2 = torch.cat([-two, one],dim=-1)
tmp2.flatten()

tensor([-1,  0, -3,  2, -5,  4, -7,  6, -9,  8])